# Generated by Django 5.0 on 2023-12-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cd', 'Card'), ('ch', 'Cash'), ('on', 'Online')], max_length=10)),
                ('payment', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('cancelling', 'Cancelling')], max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
